In [13]:
import os
os.environ['KAGGLE_USERNAME'] = "sonmyunggyun"
os.environ["KAGGLE_KEY"] = "cc39395ec842b17bd2da840b6dd64eaf"

In [12]:
!kaggle datasets download -d andrewmvd/heart-failure-clinical-data

heart-failure-clinical-data.zip: Skipping, found more recently modified local copy (use --force to force download)

In [8]:
!ls

heart-failure-clinical-data.zip  sample_data

In [10]:
!unzip "*.zip"

Archive:  heart-failure-clinical-data.zip
  inflating: heart_failure_clinical_records_dataset.csv

In [11]:
!ls

heart-failure-clinical-data.zip		    sample_data
heart_failure_clinical_records_dataset.csv

In [14]:
import numpy as np
import pandas as pd

In [15]:
df = pd.read_csv("heart_failure_clinical_records_dataset.csv")

In [16]:
df

      age  anaemia  creatinine_phosphokinase  ...  smoking  time  DEATH_EVENT
0    75.0        0                       582  ...        0     4            1
1    55.0        0                      7861  ...        0     6            1
2    65.0        0                       146  ...        1     7            1
3    50.0        1                       111  ...        0     7            1
4    65.0        1                       160  ...        0     8            1
..    ...      ...                       ...  ...      ...   ...          ...
294  62.0        0                        61  ...        1   270            0
295  55.0        0                      1820  ...        0   271            0
296  45.0        0                      2060  ...        0   278            0
297  45.0        0                      2413  ...        1   280            0
298  50.0        0                       196  ...        1   285            0

[299 rows x 13 columns]

In [18]:
df.describe()

              age     anaemia  ...        time  DEATH_EVENT
count  299.000000  299.000000  ...  299.000000    299.00000
mean    60.833893    0.431438  ...  130.260870      0.32107
std     11.894809    0.496107  ...   77.614208      0.46767
min     40.000000    0.000000  ...    4.000000      0.00000
25%     51.000000    0.000000  ...   73.000000      0.00000
50%     60.000000    0.000000  ...  115.000000      0.00000
75%     70.000000    1.000000  ...  203.000000      1.00000
max     95.000000    1.000000  ...  285.000000      1.00000

[8 rows x 13 columns]

In [21]:
import seaborn as sns
sns.histplot(x = "ejection_fraction", data = df. hue = 'DEATH_EVENT')

SyntaxError: ignored

In [22]:
X_num = df[['age', 'creatinine_phosphokinase', 'ejection_fraction','platelets', 'serum_creatinine', 'serum_sodium', 'time']]
X_cat = df[['anaemia', 'diabetes', 'high_blood_pressure', 'sex', 'smoking']]
y = df[['DEATH_EVENT']]
print(X_num)

      age  creatinine_phosphokinase  ...  serum_sodium  time
0    75.0                       582  ...           130     4
1    55.0                      7861  ...           136     6
2    65.0                       146  ...           129     7
3    50.0                       111  ...           137     7
4    65.0                       160  ...           116     8
..    ...                       ...  ...           ...   ...
294  62.0                        61  ...           143   270
295  55.0                      1820  ...           139   271
296  45.0                      2060  ...           138   278
297  45.0                      2413  ...           140   280
298  50.0                       196  ...           136   285

[299 rows x 7 columns]

In [28]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(X_num)
x_scaled = ss.transform(X_num)

In [29]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(x_scaled, y, test_size = 0.3, random_state = 1)

In [31]:
from sklearn.linear_model import LogisticRegression

model_lr = LogisticRegression(max_iter = 1000)
model_lr.fit(train_input, train_target)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [32]:
print(model_lr.score(train_input, train_target))
print(model_lr.score(test_input, test_target))

0.8277511961722488
0.8222222222222222

In [38]:
from sklearn.metrics import classification_report
pred = model_lr.predict(test_input)
print(classification_report(test_target, pred))

              precision    recall  f1-score   support

           0       0.86      0.89      0.88        64
           1       0.71      0.65      0.68        26

    accuracy                           0.82        90
   macro avg       0.79      0.77      0.78        90
weighted avg       0.82      0.82      0.82        90